##############
# ğŸ™ Argo Sync Policy
#############
sync_policy_true: &sync_policy_true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true

##############
# ğŸ› Argo App of Apps. Points to a repo which contains some helm stuff
#############

applications:
  - name: yaml-online-dev
    destination: develop
    enabled: true
    source: https://github.com/caiomedeirospinto/ocp-cicd-demo
    source_path: charts/ubiquitous-journey
    source_ref: master
    sync_policy: *sync_policy_true
  - name: charts-deploy
    destination: nexus
    enabled: true
    source: https://github.com/caiomedeirospinto/ocp-cicd-demo
    source_path: .iac/
    source_ref: master
    sync_policy: *sync_policy_true
